AWSTemplateFormatVersion: '2010-09-09'
Description: Birinci VPC yaradiriq
Parameters:
    VpcName:
        Type: String
        Default: MyVPC
    VpcCidr:
        Type: String
        Default: 10.0.0.0/16
    PublicSubnetName:
        Type: String
        Default: MyPubSub
    PublicSubnet2Name:
        Type: String
        Default: MyPubSub2       
    PublicSubnetAz:
        Type: String
        Default: us-east-2a
    PublicSubnet2Az:
        Type: String
        Default: us-east-2c        
    PublicSubnetCidr:
        Type: String
        Default: 10.0.0.0/24
    PublicSubnet2Cidr:
        Type: String
        Default: 10.0.8.0/24        
    RouteTableName:
        Type: String
        Default: Route
    IntgatewayName:
        Type: String
        Default: intgateway
    
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: !Ref VpcCidr
          EnableDnsSupport: true
          EnableDnsHostnames: true
          InstanceTenancy: default
          Tags:
            - Key: Name
              Value: !Ref VpcName
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        DependsOn: VPC
        Properties:
            Tags:
              - Key: Name
                Value: !Ref IntgatewayName
              - Key: Network
                Value: Public
    EIP:
        Type: AWS::EC2::EIP
        Properties:
            Domain: vpc
    VPCGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC
    PublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            MapPublicIpOnLaunch: true
            VpcId: !Ref VPC
            AvailabilityZone: !Ref PublicSubnetAz
            CidrBlock: !Ref PublicSubnetCidr
            Tags:
              - Key: Name
                Value: !Ref PublicSubnetName
    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            MapPublicIpOnLaunch: true
            VpcId: !Ref VPC
            AvailabilityZone: !Ref PublicSubnet2Az
            CidrBlock: !Ref PublicSubnet2Cidr
            Tags:
            - Key: Name
              Value: !Ref PublicSubnet2Name                

    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId: !Ref VPC
          Tags:
            - Key: Name
              Value: !Ref RouteTableName

    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: VPCGatewayAttachment
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: "0.0.0.0/0"
            GatewayId: !Ref InternetGateway

    PublicSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet
    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId: !Ref PublicRouteTable
          SubnetId: !Ref PublicSubnet2            
 
Outputs:
    VPC:
        Description: A reference to the created VPC
        Value: !Ref VPC
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}-VPC"

    InternetGateway:
        Description: Internet gateway for application
        Value: !Ref InternetGateway

    EIP:
        Description: Elastic IP
        Value: !Ref EIP
        
    VPCGatewayAttachment:
        Description: VPC gateway attachment for application
        Value: !Ref VPCGatewayAttachment

    PublicRouteTable:
        Description: Internet gateway attachment for application
        Value: !Ref PublicRouteTable

    DefaultPublicRoute:
        Description: Default public route
        Value: !Ref DefaultPublicRoute

    PublicSubnetRouteTableAssociation:
        Description: Associate subnet one with route table
        Value: !Ref PublicSubnetRouteTableAssociation
    PublicSubnet2RouteTableAssociation:
        Description: Associate subnet two with route table
        Value: !Ref PublicSubnet2RouteTableAssociation        
    PublicSubnet:
        Description: A reference to the public subnet in the 1st Availability Zone
        Value: !Ref PublicSubnet
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}-PublicSubnet"
    PublicSubnet2:
        Description: A reference to the public subnet in the 2nd Availability Zone
        Value: !Ref PublicSubnet2
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}-PublicSubnet2"
